name: flutter_web_scanner
description: Flutter Web barcode scanner

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  http: ^1.2.0
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
